title: JackLovel's blog
email: 
description: ""
baseurl: ""
url: ""
twitter_username: ""
github_username: ""
timezone: CST

# Build settings
markdown: kramdown
theme: minima
plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
